matrix:
  include:
    - language: python
      python: 2.7
      script:
        - python get_centroid.py

    - language: r
      script:
        - Rscript pre_processing.R

notifications:
  email:
    - zhao-tx16@mails.tsinghua.edu.cn
